INSERT INTO `pages` (`id`, `label`, `parent_id`, `title`, `slug`, `body`, `excerpt`, `featured_image`, `template`, `publish_status`, `published_at`, `created_at`, `updated_at`, `deleted_at`) VALUES
                                                                                                                                                                                                   (1, 'home page', 0, 'laratek', 'home', NULL, NULL, '/storage/uploads/pages/laratek-featured_image.jpg', NULL, 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (2, 'blog index', 0, 'blog', 'blog', NULL, NULL, '/storage/uploads/pages/blog-featured_image.jpg', NULL, 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (3, 'services index', 0, 'services', 'services', NULL, NULL, '/storage/uploads/pages/services-featured_image.jpg', NULL, 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (4, 'portfolios index', 0, 'portfolios', 'portfolios', NULL, NULL, '/storage/uploads/pages/portfolios-featured_image.jpg', NULL, 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (5, 'team index', 0, 'team', 'team', NULL, NULL, '/storage/uploads/pages/team-featured_image.jpg', 'team', 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (9, 'search page', 0, 'search', 'search', NULL, NULL, '/storage/uploads/pages/team-featured_image.jpg', null, 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (10, NULL, 0, 'contact', 'contact', NULL, NULL, '/storage/uploads/pages/contact-featured_image.jpg', 'contact', 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL),
                                                                                                                                                                                                   (11, NULL, 0, 'about', 'about', NULL, NULL, '/storage/uploads/pages/about-featured_image.jpg', 'about', 1, NULL, '2025-09-15 06:56:19', '2025-09-15 06:56:19', NULL);
