INSERT INTO `products_properties` (`product_id`, `property_id`) VALUES
                                                                    (3, 1),
                                                                    (1, 4),
                                                                    (4, 4),
                                                                    (1, 5),
                                                                    (4, 5),
                                                                    (2, 7),
                                                                    (2, 8),
                                                                    (5, 9),
                                                                    (2, 11),
                                                                    (3, 11),
                                                                    (4, 11),
                                                                    (1, 12),
                                                                    (5, 12),
                                                                    (1, 16),
                                                                    (4, 19),
                                                                    (1, 20);
