INSERT INTO `menu_items` (`id`, `menu_id`, `parent_id`, `position`, `title`, `subtitle`, `pre_icon`, `next_icon`, `image`, `url`, `classes`, `attributes`, `created_at`, `updated_at`) VALUES
                                                                                                                                                                                           (1, 1, NULL, 9, 'with laratek', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (2, 1, 1, 11, 'team', NULL, NULL, NULL, NULL, '/team', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (3, 1, 1, 10, 'about', NULL, NULL, NULL, NULL, '/about', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (4, 1, 1, 12, 'contact', NULL, NULL, NULL, NULL, '/contact', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (7, 1, NULL, 0, 'home', NULL, NULL, NULL, NULL, '/', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (8, 1, NULL, 1, 'graphic', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (9, 1, 8, 2, 'graphics', NULL, NULL, NULL, NULL, '/services/graphic-design', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (10, 1, 8, 3, 'logo', NULL, NULL, NULL, NULL, '/services/logo-design', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (11, 1, 8, 4, 'QR code', NULL, NULL, NULL, NULL, '/services/qr-code', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (12, 1, NULL, 5, 'web', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (13, 1, 12, 6, 'website', NULL, NULL, NULL, NULL, '/services/web-design', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (14, 1, 12, 7, 'wordpress', NULL, NULL, NULL, NULL, '/services/wordpress', NULL, NULL, NULL, NULL),
                                                                                                                                                                                           (15, 1, 12, 8, 'custom cms', NULL, NULL, NULL, NULL, '/services/custom-cms', NULL, NULL, NULL, NULL)
