INSERT INTO `seo_models` (`id`, `model_type`, `model_id`, `title`, `description`, `keywords`, `conical_url`, `indexable`, `followable`, `seo_type`, `schema`, `created_at`, `updated_at`) VALUES
                                                                                                                                                                                              (1, 'Lareon\\Modules\\Page\\App\\Models\\Page', 1, 'Laratek – Graphic Design & Website Development Services', 'Creative logo & QR code design, WordPress sites, and custom CMS solutions by Laratek. Modern digital services for brands that want to stand out', '[\"\"]', NULL, 1, 1, 'webPage', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),
                                                                                                                                                                                              (2, 'Lareon\\Modules\\Page\\App\\Models\\Page', 2, 'Blog – Insights on Design & Web Development by Laratek', 'Explore the Laratek blog for articles on design trends, WordPress tips, and custom CMS solutions. Learn, get inspired, and grow your digital presence.', '[\"\"]', 'https://laratek.net//blog', 1, 1, 'webPage', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),
                                                                                                                                                                                              (10, 'Lareon\\Modules\\Page\\App\\Models\\Page', 10, 'Contact Us – Get in Touch with Laratek', 'Have a project in mind? Contact Laratek today for graphic design, WordPress websites, and custom CMS solutions. We’re here to help your business grow.', '[\"\"]', 'https://laratek.net//contact', 1, 1, 'webPage', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),
                                                                                                                                                                                              (11, 'Lareon\\Modules\\Page\\App\\Models\\Page', 11, 'About Us – Learn More About Laratek', 'laratek is googLaratek is a creative team specializing in graphic design, WordPress, and custom CMS. Learn more about our story, vision, and commitment to clients.', '[\"laravel\", \"laratek\", \"lareon\"]', 'https://laratek.net//about', 1, 1, 'webPage', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),
                                                                                                                                                                                              (12, 'Lareon\\Modules\\Page\\App\\Models\\Page', 12, 'consultation', NULL, '[\"\"]', 'https://laratek.net/consultation', 1, 1, 'webPag', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),

                                                                                                                                                                                              (22, 'Lareon\\Modules\\Page\\App\\Models\\Page', 5, 'Our Team – Meet the Experts Behind Laratek', 'Discover the Laratek team of skilled designers and developers who bring your ideas to life with expertise in graphics, WordPress, and custom CMS.', '[\"\"]', NULL, 1, 1, 'webPage', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),
                                                                                                                                                                                              (23, 'Lareon\\Modules\\Page\\App\\Models\\Page', 4, 'Portfolios – Our Creative Works at Laratek', 'Discover Laratek’s portfolio showcasing graphic design, WordPress, and custom CMS works. Real projects that highlight creativity and innovation.', '[\"\"]', NULL, 1, 1, 'webPage', '[]', '2025-09-15 03:26:19', '2025-09-15 03:26:19'),
                                                                                                                                                                                              (26, 'Lareon\\Modules\\Product\\App\\Models\\Product', 1, NULL, NULL, '[\"\"]', NULL, 0, 0, 'webPage', '[]', '2025-09-23 04:27:23', '2025-09-23 04:27:23'),
                                                                                                                                                                                              (27, 'Lareon\\Modules\\Product\\App\\Models\\Product', 2, NULL, NULL, '[\"\"]', NULL, 0, 0, 'webPage', '[]', '2025-09-23 04:36:31', '2025-09-23 04:36:31');
